name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "* * * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        debug-only: true
        days-before-stale: 60
        days-before-close: 7
        stale-issue-label: 'stale'
        only-labels: 'enhancement'
        skip-stale-pr-message: true
        skip-stale-issue-message: true
